--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t laxi/node-server ."
      - "docker tag laxi/node-server laxi/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push laxi/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"laxmikant04\" --password=\"L@xikant94\""
version: 0.1
