--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t laxmikant04/node-server -f ./Docker/DockerFile ."
      - "docker tag laxmikant04/node-server laxmikant04/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push laxmikant04/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"laxmikant04\" --password=\"L@xikant94\""
artifacts:
  files:
    - '**/*'
  discard-paths: yes
version: 0.1
